/*
# Create clients table for Sistema de Aportes Mensuales

1. Purpose
   Stores the full client/plan/payment records for the "Sistema de Aportes
   Mensuales" app. Each row represents a single client with their payment plan,
   table of installments (as JSONB), and collection-management history.

2. New Tables
   - `clients`
     - `id` (text, primary key) — stable client id generated by the app
     - `nombres` (text) — client full name
     - `doc_identidad` (text) — identity document number
     - `ejecutivo_cartera` (text) — assigned executive
     - `tipo_plan` (text) — plan type
     - `estado_activo` (text) — active/disabled status
     - `grupo_codigo` (text) — group/code
     - `monto_contratado` (numeric) — contracted amount
     - `valor_inscripcion` (numeric) — inscription fee
     - `plazo_plan` (integer) — plan term in months
     - `valor_cuota` (numeric) — monthly installment
     - `estado_plan` (text) — adjudication status
     - `forma_adjudicacion` (text) — adjudication method
     - `fecha_adjudicacion` (date) — adjudication date
     - `numero_asamblea` (text) — assembly number
     - `fecha_entrega` (date) — delivery date
     - `cuotas_pagadas` (integer) — paid installments count
     - `fecha_primer_pago` (date) — first payment date
     - `valor_entrada` (numeric) — entry value
     - `porcentaje_entrada` (numeric) — entry percentage
     - `fecha_pago_entrada` (date) — entry payment date
     - `total_plan` (numeric) — total plan value
     - `table_data` (jsonb) — installment schedule rows
     - `gestiones` (jsonb) — management history entries
     - `cuotas_vencidas_excel` (integer) — overdue installments (from Excel)
     - `valor_vencido_excel` (numeric) — overdue amount (from Excel)
     - `created_at` (timestamptz) — record creation timestamp

3. Security
   - Enable RLS on `clients`.
   - Single-tenant app (no sign-in): allow anon + authenticated full CRUD,
     because the data is intentionally shared/public.
*/

CREATE TABLE IF NOT EXISTS clients (
  id text PRIMARY KEY,
  nombres text NOT NULL DEFAULT '',
  doc_identidad text NOT NULL DEFAULT '',
  ejecutivo_cartera text NOT NULL DEFAULT 'Sin Asignar',
  tipo_plan text NOT NULL DEFAULT 'Compra Planificada',
  estado_activo text NOT NULL DEFAULT 'Activo',
  grupo_codigo text NOT NULL DEFAULT '',
  monto_contratado numeric NOT NULL DEFAULT 0,
  valor_inscripcion numeric NOT NULL DEFAULT 0,
  plazo_plan integer NOT NULL DEFAULT 0,
  valor_cuota numeric NOT NULL DEFAULT 0,
  estado_plan text NOT NULL DEFAULT 'No Adjudicado',
  forma_adjudicacion text NOT NULL DEFAULT '',
  fecha_adjudicacion date,
  numero_asamblea text NOT NULL DEFAULT '',
  fecha_entrega date,
  cuotas_pagadas integer NOT NULL DEFAULT 0,
  fecha_primer_pago date,
  valor_entrada numeric NOT NULL DEFAULT 0,
  porcentaje_entrada numeric NOT NULL DEFAULT 0,
  fecha_pago_entrada date,
  total_plan numeric NOT NULL DEFAULT 0,
  table_data jsonb NOT NULL DEFAULT '[]'::jsonb,
  gestiones jsonb NOT NULL DEFAULT '[]'::jsonb,
  cuotas_vencidas_excel integer NOT NULL DEFAULT 0,
  valor_vencido_excel numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_clients" ON clients;
CREATE POLICY "anon_select_clients" ON clients FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_clients" ON clients;
CREATE POLICY "anon_insert_clients" ON clients FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_clients" ON clients;
CREATE POLICY "anon_update_clients" ON clients FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_clients" ON clients;
CREATE POLICY "anon_delete_clients" ON clients FOR DELETE
  TO anon, authenticated USING (true);
